Repository l3r8yJ/screener-api, pull requests merged in 2022-09, with the labels that each got.

#19 Auth refactored
  src/main/java/ru/leroy/screenerapi/service/UserService.java
Labels: enhancement

#20 pass upd tests
  src/main/java/ru/leroy/screenerapi/exception/SamePasswordException.java
  src/main/java/ru/leroy/screenerapi/service/UserService.java
  src/test/java/ru/leroy/screenerapi/service/UserServiceTest.java
Labels: tests

#22 100% user service code cov
  src/main/java/ru/leroy/screenerapi/exception/SameRateException.java
  src/main/java/ru/leroy/screenerapi/service/UserService.java
  src/test/java/ru/leroy/screenerapi/service/UserServiceTest.java
Labels: tests

#26 9% user controller coverage
  pom.xml
  src/main/java/ru/leroy/screenerapi/controller/UserController.java
  src/test/java/ru/leroy/screenerapi/controller/UserControllerTest.java
  src/test/java/ru/leroy/screenerapi/service/UserServiceTest.java
Labels: enhancement, tests

#34 #33-info-tests-in-usercontroller info user success test
  pom.xml
  src/test/java/ru/leroy/screenerapi/controller/UserControllerTest.java
Labels: tests

#35 #33-info-tests-in-usercontroller
  src/test/java/ru/leroy/screenerapi/controller/UserControllerTest.java
Labels: tests

#44 tests for all cases in rate update
  src/test/java/ru/leroy/screenerapi/controller/UserControllerTest.java
Labels: tests

#45 30 authentication tests in usercontroller
  src/test/java/ru/leroy/screenerapi/controller/UserControllerTest.java
Labels: tests

#47 #46-use-copy-instead-of-add-for-files-and-folders fixed
  Dockerfile
Labels: bug

#48 30 authentication tests in usercontroller
  src/test/java/ru/leroy/screenerapi/controller/UserControllerTest.java
Labels: enhancement

#50 29-registration-tests-in-usercontroller
  src/test/java/ru/leroy/screenerapi/controller/UserControllerTest.java
Labels: tests

#68 #67-dry-in-usercontroller fixed routes, dry fixed
  src/main/java/ru/leroy/screenerapi/controller/UserController.java
  src/test/java/ru/leroy/screenerapi/controller/UserControllerTest.java
Labels: bug, enhancement

#74 #73-fix-codesmell-in-user-controller fixes
  src/main/java/ru/leroy/screenerapi/controller/UserController.java
  src/main/java/ru/leroy/screenerapi/message/RateNames.java
  src/test/java/ru/leroy/screenerapi/ScreenerApiApplicationTest.java
Labels: enhancement, checkstyle

#82 53-market-repository
  src/main/java/ru/leroy/screenerapi/repository/MarketRepository.java
Labels: enhancement

#84 54-market-service
  src/main/java/ru/leroy/screenerapi/service/MarketService.java
Labels: enhancement

#87 #86-usercontroller-registration-exception-handling
  src/main/java/ru/leroy/screenerapi/controller/UserController.java
Labels: bug
